DROP TABLE IF EXISTS BOOK_CATEGORY;
DROP TABLE IF EXISTS BOOKNEW;
  
CREATE TABLE BOOK_CATEGORY(
   ID INT  AUTO_INCREMENT  PRIMARY KEY,
   NAME VARCHAR(250) NOT NULL
  
);

CREATE TABLE BOOK_NEW(
   ID INT  AUTO_INCREMENT  PRIMARY KEY,
   NAME VARCHAR(250) NOT NULL,
   BOOK_CATEGORY_ID INT 
);